#!/bin/sh

. /lib/functions.sh
# Copy defaults by the factory to the obuspa UCI global section.
config_load obuspa

if [ -f "/lib/functions/iopsys-environment.sh" ]; then
	. /lib/functions/iopsys-environment.sh
fi

# Get Manufacturer OUI.
oui="$(get_manufacturer_oui)"
if [ -z "${oui}" ]; then
	oui=$(db -q get device.deviceinfo.ManufacturerOUI)
fi

oui=$(echo "${oui}" | tr 'a-f' 'A-F')

# Get system serial number.
serial="$(get_serial_number)"
if [ -z "${serial}" ]; then
	serial=$(db -q get device.deviceinfo.SerialNumber)
fi

username="${oui}-${serial}"

# Get username value
config_get usp_user global username ""

# Only set if they are empty or not same
if [ -z "${usp_user}" ] || [ "${usp_user}" != "${username}" ]; then
    uci -q set obuspa.global.username="${username}"
fi

default_password="$(get_acs_password)"
if [ -z "${default_password}" ]; then
	default_password="iopsys"
fi

config_get usp_pass global password ""
if [ -z "${usp_pass}" ] || [ "${usp_pass}" != "${default_password}" ]; then
	uci -q set obuspa.global.password="${default_password}"
fi

# No need for commit here, it is done by uci_apply_defaults().
